# Generated by Django 5.2.8 on 2025-11-27 20:38

import django.db.models.deletion
import quotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fault_report', '0005_faultreportimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_ref_num', models.CharField(default=None, max_length=10, null=True)),
                ('payment_status', models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=1)),
                ('total_bill', models.FloatField(default=0)),
                ('approval_status', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending Approval'), ('D', 'Disapproved'), ('C', 'Cancelled')], default='P', verbose_name=quotation.models.ApprovalStatus)),
                ('fault_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fault_report.faultreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('total_units', models.IntegerField()),
                ('per_unit_price', models.FloatField()),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation')),
            ],
        ),
    ]
