# Generated by Django 5.2.8 on 2025-11-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='per_unit_price',
            new_name='price_per_unit',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_ref_num',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
