# Generated by Django 5.2.8 on 2025-11-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_rename_per_unit_price_bill_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sales_tax',
            field=models.FloatField(default=0),
        ),
    ]
