# Generated by Django 5.2.8 on 2025-11-29 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_bill_created_at_quotation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='quotation.quotation'),
        ),
    ]
