# Generated by Django 5.2.8 on 2025-11-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_alter_bill_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sub_total_bill',
            field=models.FloatField(default=0),
        ),
    ]
