# Generated by Django 5.2.8 on 2025-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_quotation_sub_total_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='email_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
