# Generated by Django 5.2.8 on 2025-11-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_quotation_email_link_quotation_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='email_link',
        ),
        migrations.AddField(
            model_name='quotation',
            name='email_code',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
