# Generated by Django 5.2.8 on 2025-12-07 19:39

import quotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_remove_quotation_email_link_quotation_email_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='approval_status',
            field=models.CharField(choices=[('QA', 'Approved'), ('QP', 'Pending Approval'), ('QD', 'Disapproved'), ('QC', 'Cancelled')], default='QP', verbose_name=quotation.models.ApprovalStatus),
        ),
    ]
