# Generated by Django 5.2.8 on 2025-11-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_available_user_is_enduser_user_is_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
