# Generated by Django 5.2.8 on 2026-01-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change_password_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
