# Generated by Django 5.2.8 on 2026-01-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_change_password_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='change_password_link',
            new_name='change_password_code',
        ),
    ]
