# Generated by Django 5.2.8 on 2026-02-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_change_password_link_user_change_password_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_activation_code',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
