# Generated by Django 5.2.8 on 2026-02-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_account_activation_code'),
        ('address', '0002_alter_organization_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_location',
            field=models.ManyToManyField(related_name='user_location', to='address.location'),
        ),
    ]
