# Generated by Django 5.2.8 on 2026-03-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_account_number_user_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internal_creation',
            field=models.BooleanField(default=False),
        ),
    ]
