# Generated by Django 5.2.8 on 2026-03-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_internal_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='internal_creation',
        ),
    ]
