# Generated by Django 5.2.8 on 2026-03-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_internal_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
