# Generated by Django 5.2.8 on 2025-11-24 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0002_remove_faultreport_technician_and_more'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faultreport',
            old_name='contact_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='faultreport',
            name='job_description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='job',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='note',
            field=models.TextField(default=None, null=True),
        ),
    ]
