# Generated by Django 5.2.8 on 2025-11-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0003_rename_contact_location_faultreport_location_and_more'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.status'),
        ),
    ]
