# Generated by Django 5.2.8 on 2025-11-24 21:09

import django.db.models.deletion
import fault_report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0004_alter_faultreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=fault_report.models.saveFaultReportImage)),
                ('fault_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fault_report.faultreport')),
            ],
        ),
    ]
