# Generated by Django 5.2.8 on 2025-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0005_faultreportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='completed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='started_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
