# Generated by Django 5.2.8 on 2025-12-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0006_faultreport_completed_at_faultreport_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='priority_level',
            field=models.CharField(default='L', max_length=2, verbose_name=[('U', 'Urgent'), ('H', 'High'), ('M', 'Moderate'), ('L', 'Low')]),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('QS', 'Quote sent'), ('QA', 'Quote approved'), ('A', 'Assigned'), ('IP', 'In progress'), ('P', 'Paused'), ('C', 'Completed')], default='S', max_length=2),
        ),
    ]
