# Generated by Django 5.2.8 on 2025-12-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0007_alter_faultreport_priority_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='priority_level',
            field=models.CharField(default='L', max_length=2, verbose_name=[('L', 'Low'), ('M', 'Moderate'), ('H', 'High'), ('U', 'Urgent')]),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('QS', 'Quote sent'), ('QA', 'Quote approved'), ('QD', 'Quote disapproved'), ('QC', 'Quote disapproved'), ('A', 'Assigned'), ('IP', 'In progress'), ('P', 'Paused'), ('C', 'Completed')], default='S', max_length=2),
        ),
    ]
