# Generated by Django 5.2.8 on 2025-12-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0008_alter_faultreport_priority_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultreport',
            name='deadline',
        ),
    ]
