# Generated by Django 5.2.8 on 2025-12-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0009_remove_faultreport_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='deadline',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='deadline_time_unit',
            field=models.CharField(choices=[('H', 'Hour'), ('D', 'Day'), ('M', 'Month'), ('Y', 'Year')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='priority_level',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Moderate'), ('H', 'High'), ('U', 'Urgent')], default='L', max_length=2),
        ),
    ]
