# Generated by Django 5.2.8 on 2025-12-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0010_faultreport_deadline_faultreport_deadline_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
