# Generated by Django 5.2.8 on 2025-12-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0011_faultreport_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
