# Generated by Django 5.2.8 on 2025-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0012_faultreport_is_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='completion_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='deadline_time_unit',
            field=models.CharField(choices=[('H', 'Hour'), ('D', 'Day')], default='D', max_length=1),
        ),
    ]
