# Generated by Django 5.2.8 on 2026-01-25 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0013_faultreport_completion_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='user_technician',
            field=models.ManyToManyField(default=None, null=True, related_name='fault_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
