# Generated by Django 5.2.8 on 2026-02-01 07:18

import fault_report.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0014_alter_faultreport_user_technician'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='preferred_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='faultreportimage',
            name='completion_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=fault_report.models.saveCompletionImage),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='user_technician',
            field=models.ManyToManyField(related_name='fault_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
