# Generated by Django 5.2.8 on 2026-02-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_organization_location'),
        ('fault_report', '0015_faultreport_preferred_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='address',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.location'),
        ),
    ]
