# Generated by Django 5.2.8 on 2026-02-10 17:34

import django.db.models.deletion
import fault_report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0016_faultreport_address_alter_faultreport_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultreport',
            name='fault_id',
        ),
        migrations.RemoveField(
            model_name='faultreportimage',
            name='completion_image',
        ),
        migrations.AddField(
            model_name='faultreport',
            name='job_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('PS', 'Pending submission'), ('S', 'Submitted'), ('QS', 'Quote sent'), ('QA', 'Quote approved'), ('QD', 'Quote disapproved'), ('QC', 'Quote disapproved'), ('A', 'Assigned'), ('IP', 'In progress'), ('P', 'Paused'), ('C', 'Completed')], default='PS', max_length=2),
        ),
        migrations.CreateModel(
            name='CompletionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=fault_report.models.saveCompletionImage)),
                ('fault_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fault_report.faultreport')),
            ],
        ),
    ]
