# Generated by Django 5.2.8 on 2026-02-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0017_remove_faultreport_fault_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='if_recall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='po_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('PS', 'Pending submission'), ('S', 'Submitted'), ('QS', 'Quote sent'), ('QA', 'Quote approved'), ('QC', 'Quote canceled'), ('A', 'Assigned'), ('IP', 'In progress'), ('P', 'Paused'), ('C', 'Completed')], default='PS', max_length=2),
        ),
    ]
