# Generated by Django 5.2.8 on 2026-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0018_faultreport_if_recall_faultreport_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='sent_assignment_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='sent_completion_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='sent_submission_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('QS', 'Quote sent'), ('QA', 'Quote approved'), ('QC', 'Quote canceled'), ('A', 'Assigned'), ('IP', 'In progress'), ('P', 'Paused'), ('C', 'Completed')], default='S', max_length=2),
        ),
    ]
