# Generated by Django 5.2.8 on 2025-12-02 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0008_remove_quotation_email_link_quotation_email_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('notif_by_id', models.IntegerField(default=None)),
                ('notif_for_id', models.IntegerField(default=None)),
                ('notif_area', models.CharField(choices=[('Q', 'Quotation'), ('A', 'Assignment'), ('S', 'Summarize')], default=None, max_length=1)),
                ('is_opened', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quotation_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation')),
            ],
        ),
    ]
