# Generated by Django 5.2.8 on 2025-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_area',
            field=models.CharField(choices=[('F', 'Fault report'), ('Q', 'Quotation'), ('A', 'Assignment'), ('S', 'Summarize')], default=None, max_length=1),
        ),
    ]
