# Generated by Django 5.2.8 on 2025-12-02 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0005_faultreportimage'),
        ('notification', '0002_alter_notification_notif_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='fault_report_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fault_report.faultreport'),
        ),
    ]
