# Generated by Django 5.2.8 on 2025-12-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_fault_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='quotation_id',
        ),
    ]
