# Generated by Django 5.2.8 on 2025-12-02 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_assignment_id_and_more'),
        ('quotation', '0008_remove_quotation_email_link_quotation_email_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='quotation_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation'),
        ),
    ]
