# Generated by Django 5.2.8 on 2025-12-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_quotation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='fault_report_id',
            new_name='fault_report',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='quotation_id',
            new_name='quotation',
        ),
    ]
