# Generated by Django 5.2.8 on 2025-12-02 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_report', '0005_faultreportimage'),
        ('notification', '0006_rename_fault_report_id_notification_fault_report_and_more'),
        ('quotation', '0008_remove_quotation_email_link_quotation_email_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='fault_report',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fault_report.faultreport'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='quotation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation'),
        ),
    ]
