# Generated by Django 5.2.8 on 2025-12-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_notification_fault_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_by_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_for_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
