# Generated by Django 5.2.8 on 2026-04-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('post_code', models.CharField(max_length=12)),
                ('region', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contract_no1', models.CharField(max_length=20)),
                ('contract_no2', models.CharField(default=None, max_length=20, null=True)),
                ('ethnicity', models.CharField(default=None, max_length=30, null=True)),
                ('reliability_max', models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True)),
                ('travel_radius', models.DecimalField(decimal_places=2, default=None, max_digits=7, null=True)),
                ('vehicle', models.BooleanField(default=False)),
                ('out_of_hour', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('rates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('specialities', models.TextField()),
                ('insurance', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
