# Generated by Django 5.2.8 on 2026-04-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='contract_no1',
            new_name='contact_no1',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='contract_no2',
            new_name='contact_no2',
        ),
    ]
