# Generated by Django 5.2.8 on 2026-04-21 17:02

import contractor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_rename_contract_no1_worker_contact_no1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=contractor.models.saveWorkerPhoto),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
