# Generated by Django 5.2.8 on 2026-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_worker_photo_alter_worker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
