# Generated by Django 5.2.8 on 2026-04-24 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0004_alter_worker_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='note',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='specialities',
            field=models.TextField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='WorkerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(default=None, max_length=10, null=True)),
                ('po_number', models.CharField(default=None, max_length=255, null=True)),
                ('ref', models.CharField(default=None, max_length=20, null=True)),
                ('charge', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('date_completed', models.DateTimeField()),
                ('signed_by', models.CharField(default=None, max_length=100, null=True)),
                ('note', models.TextField(default=None, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractor.worker')),
            ],
        ),
    ]
