# Generated by Django 5.2.8 on 2026-05-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0005_alter_worker_note_alter_worker_specialities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='expiry_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
