# Generated by Django 5.2.8 on 2026-02-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ManyToManyField(related_name='location', to='address.location'),
        ),
    ]
