# Generated by Django 5.2.8 on 2025-12-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
