# Generated by Django 5.2.8 on 2025-12-21 19:53

import front_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0002_rename_customer_id_customerreview_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member_id',
            new_name='member',
        ),
        migrations.AddField(
            model_name='team',
            name='designation',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member_image',
            field=models.ImageField(default='front_page/default_profile.png', upload_to=front_page.models.saveMemberImage),
        ),
    ]
