# Generated by Django 5.2.8 on 2025-12-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0003_rename_member_id_team_member_team_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
