# Generated by Django 5.2.8 on 2025-12-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0004_team_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member_name',
        ),
    ]
