# Generated by Django 5.2.8 on 2025-12-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority_level', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriorityLevel',
        ),
    ]
