# Generated by Django 5.2.8 on 2026-04-13 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_item_category_alter_item_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='property.item'),
        ),
    ]
