# Generated by Django 5.2.8 on 2025-12-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
